# Generated by Django 4.0 on 2022-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='clothes/')),
                ('desc', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('category', models.CharField(default='MEN', max_length=5)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='furniture/')),
                ('desc', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='jewellery/')),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='kitchen/')),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
    ]
