# Generated by Django 4.0 on 2022-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
    ]
