# Generated by Django 3.2.10 on 2022-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('discount', models.CharField(default='0', max_length=3)),
            ],
        ),
    ]
