# Generated by Django 3.2.10 on 2022-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0005_alter_orders_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('img', models.FileField(default=None, max_length=250, null=True, upload_to='products/')),
                ('desc', models.TextField()),
                ('productCategory', models.CharField(max_length=100)),
                ('category', models.CharField(default='clothes', max_length=50)),
                ('cost', models.FloatField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
