# Generated by Django 3.2.10 on 2022-04-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0007_auto_20220407_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productName',
            new_name='title',
        ),
    ]
