# Generated by Django 4.0 on 2022-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0009_auto_20220409_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kitchen',
        ),
    ]
