# Generated by Django 4.0 on 2022-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0010_delete_kitchen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='furniture',
        ),
        migrations.DeleteModel(
            name='jewellery',
        ),
    ]
