# Generated by Django 4.0 on 2022-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0011_delete_furniture_delete_jewellery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothes',
        ),
    ]
