# Generated by Django 3.2.10 on 2022-04-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0012_delete_clothes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
