# Generated by Django 3.2.10 on 2022-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
