# Generated by Django 3.2.10 on 2022-04-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0015_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='img',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='title',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='shopIn.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopIn.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
