# Generated by Django 3.2.10 on 2022-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0016_auto_20220414_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
