# Generated by Django 3.2.10 on 2022-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0017_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
