# Generated by Django 3.2.10 on 2022-04-15 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopIn', '0018_alter_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], default='pending', max_length=9),
        ),
    ]
